services:
    
    postgres: 
      container_name: postgres
      image: postgres:alpine
      restart: always
      networks:
        - postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: photos

      ports:
        - "5432:5432"       
###############################################################################################################
    pgadmin:
      container_name: pgadmin
      networks:
        - postgres
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: root@root.com
          PGADMIN_DEFAULT_PASSWORD: root
      ports:
         - "5050:80"
    
networks:
  postgres:
    driver: bridge
