services:
    
    postgres: 
      container_name: postgres
      platform: linux/amd64  
      image: postgres:alpine
      restart: always
      networks:
        - postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: photos

      ports:
        - "5432:5432"       
###############################################################################################################
    pgadmin:
      container_name: pgadmin
      platform: linux/amd64 
      networks:
        - postgres
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: root@root.com
          PGADMIN_DEFAULT_PASSWORD: root
      ports:
         - "5050:80"

    security_camera:
      image: ghcr.io/nikhil364/motion_camera:0.0.1
      container_name: security_camera
      restart: always
      networks:
        - postgres
      devices:
        - /dev/video0:/dev/video0     
      volumes:
          - .:/app   # Mount the current directory to /app in the container
          - ./photos:/app/photos
          - ./extracted_photos_for_viewing:/app/extracted_photos_for_viewing
          - /app/photos
          - /app/extracted_photos_for_viewing
      command: ["tail", "-f", "/dev/null"] # Command to keep the container running forever
        
    
networks:
  postgres:
    driver: bridge
